---
### CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.secret.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.secret.serviceName }}
spec:
  ports:
  - port: {{ .Values.secret.servicePort }}
    protocol: TCP
  selector:
    app: {{ .Values.cspName }}

---
### CSP deployment ###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.cspName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.cspName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.cspName }}
    spec:
      serviceAccount: hpe-csp-sa
      hostNetwork: true
      containers:
        - name: {{ .Values.cspName }}
          image: {{ .Values.images.cspImage}}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
          - containerPort: {{ .Values.secret.servicePort }}
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log

