---
### CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.backendType }}-csp-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.backendType }}-csp-svc
spec:
  ports:
  - port: {{ .Values.secret.servicePort }}
    protocol: TCP
  selector:
    app: {{ .Values.backendType }}-csp

---
### CSP deployment ###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.backendType }}-csp
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backendType }}-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.backendType }}-csp
    spec:
      serviceAccount: hpe-csp-sa
      hostNetwork: true
      containers:
        - name: {{ .Values.backendType }}-csp
          {{- if eq .Values.backendType "hpe3parprimera" }}
          image: hpestorage/hpe3parprimera-csp:v1.0.0
          {{- else }}
          image: hpestorage/nimble-csp:v1.1.0
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.secret.servicePort }}
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
            
