{{- if not .Values.disable.nimble }}
---
### CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: hpe-alletra-6000-and-nimble-csp-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: hpe-alletra-6000-and-nimble-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hpe-alletra-6000-and-nimble-csp

---
### CSP deployment ###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hpe-alletra-6000-and-nimble-csp
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: hpe-alletra-6000-and-nimble-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: hpe-alletra-6000-and-nimble-csp
    spec:
      serviceAccountName: hpe-csp-sa
      {{- if and (eq .Capabilities.KubeVersion.Major "1") ( ge  ( trimSuffix "+" .Capabilities.KubeVersion.Minor ) "17") }}
      priorityClassName: system-cluster-critical
      {{- end }}
      containers:
        - name: hpe-alletra-6000-and-nimble-csp
          {{- if .Values.registry }}
          image: {{ .Values.registry }}/hpestorage/hpe-alletra-6000-and-nimble-csp:v2.0.0-beta
          {{- else }}
          image: quay.io/hpestorage/hpe-alletra-6000-and-nimble-csp:v2.0.0-beta
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 30
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 30
{{- end }}
