---
### CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: nimble-csp-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: nimble-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: nimble-csp

---
### CSP deployment ###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nimble-csp
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: nimble-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: nimble-csp
    spec:
<<<<<<< HEAD
      serviceAccount: hpe-csp-sa
=======
>>>>>>> operators: Add support to deploy CSI driver as an operator
      containers:
        - name: nimble-csp
          image: {{ .Values.cspImage}}: {{- .Values.cspTag}}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
