---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: hpe-csi-scc
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostPorts: true
allowedCapabilities:
- '*'
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:hpe-csi:hpe-csi-controller-sa
- system:serviceaccount:hpe-csi:hpe-csi-node-sa
- system:serviceaccount:hpe-csi:hpe-csp-sa
- system:serviceaccount:hpe-csi:default
volumes:
- '*'