 #### Flexvolume Driver ###
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hpe-flexvolume-driver
  namespace: kube-system
  labels:
    k8s-app: hpe-flexvolume-driver
spec:
  selector:
    matchLabels:
      name: hpe-flexvolume-driver
  template:
    metadata:
      labels:
        name: hpe-flexvolume-driver
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: hpe-flexvolume-sa
      containers:
      - name: flexvolume
        image: {{ .Values.flexVolumeDriverImage}}: {{- .Values.flexVolumeDriverTag}}
        imagePullPolicy: "Always"
        lifecycle:
          preStop:
            # create empty file to let plugin signal handler to perform cleanup of config/cert/dory files
            exec:
              command: [ "/bin/sh", "-c", "touch /etc/hpe-storage/remove" ]
        env:
        - name: LOG_LEVEL
          value: info
        - name: PROVIDER_IP
          valueFrom:
            secretKeyRef:
              name: nimble-secret
              key: arrayIp
        - name: PROVIDER_USERNAME
          valueFrom:
            secretKeyRef:
              name: nimble-secret
              key: username
        - name: PROVIDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nimble-secret
              key: password
        {{- if eq .Values.flavor "nimble"}}
        - name: PROTOCOL
          valueFrom:
            secretKeyRef:
              name: nimble-secret
              key: protocol
        {{- else }}
        - name: PROTOCOL
          value: iscsi
        {{- end }}
        - name: INSECURE
          value: "false"
        - name: SCOPE
          value: global
        - name: PLUGIN_TYPE
          value: {{ .Values.pluginType }}
        volumeMounts:
        - name: podsmountdir
          mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
        {{- if eq .Values.flavor "openshift"}}
        - name: ocpmountsdir
          mountPath: /var/lib/origin
        {{- end }}
          mountPropagation: Bidirectional
        - name: legacymounts
          mountPath: /opt/nimble
          mountPropagation: Bidirectional
        - name: dev
          mountPath: /dev
        - name: libmodules
          mountPath: /lib/modules
        - name: var-log
          mountPath: /var/log
        - name: var-lib-iscsi
          mountPath: /var/lib/iscsi
        - name: exec
          mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
        - name: runlock
          mountPath: /run/lock
        - name: etc-iscsi
          mountPath: /etc/iscsi
        - name: etc-multipath
          mountPath: /etc/multipath
        - name: etc-multipath-conf
          mountPath: /etc/multipath.conf
        - name: etc-redhat-release
          mountPath: /etc/redhat-release
        - name: etc-os-release
          mountPath: /etc/os-release
        - name: etc-hpe-storage-dir
          mountPath: /etc/hpe-storage
        - name: sys
          mountPath: /sys
        - name: iscsiadm
          mountPath: /sbin/iscsiadm
        - name: config-file
          mountPath: /etc/hpe-storage/volume-driver.json
          subPath: volume-driver.json
        - name: runsystemd
          mountPath: /run/systemd
        - name: libsystemd
          mountPath: /lib/systemd/system
        - name: usrlocal
          mountPath: /usr_local
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
      volumes:
      - name: podsmountdir
        hostPath:
          path: /var/lib/kubelet
      {{- if eq .Values.flavor "openshift"}}
      - name: ocpmountsdir
        hostPath:
          path: /var/lib/origin/
      {{- end }}
      # required to handle legacy mounts from NLT based plugin. Remove this for CoreOS
      - name: legacymounts
        hostPath:
          path: /opt/nimble/
      - name: dev
        hostPath:
          path: /dev
      - name: libmodules
        hostPath:
          path: /lib/modules
      - name: var-log
        hostPath:
          path: /var/log
      - name: var-lib-iscsi
        hostPath:
          path: /var/lib/iscsi/
      - name: exec
        hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      - name: runlock
        hostPath:
          path: /run/lock
      - name: etc-iscsi
        hostPath:
          path: /etc/iscsi/
      - name: etc-multipath
        hostPath:
          path: /etc/multipath/
      - name: etc-multipath-conf
        hostPath:
          path: /etc/multipath.conf
      - name: etc-redhat-release
        hostPath:
          path: /etc/redhat-release
      - name: etc-os-release
        hostPath:
          path: /etc/os-release
      - name: etc-hpe-storage-dir
        hostPath:
          path: /etc/hpe-storage/
      - name: sys
        hostPath:
          path: /sys
      - name: iscsiadm
        hostPath:
          path: /sbin/iscsiadm
      - name: config-file
        configMap:
          name: nimble-config
      - name: runsystemd
        hostPath:
          path: /run/systemd
      - name: libsystemd
        hostPath:
          path: /lib/systemd/system
      - name: usrlocal
        hostPath:
          path: /usr
