# Default values for hpe-csi-driver Helm chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# For controlling automatic iscsi/multipath package installation
disableNodeConformance: false

# Kubelet root directory path
kubeletRootDir: "/var/lib/kubelet"

# Controller driver decorations
controller:

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  labels: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  nodeSelector: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  tolerations: []

  affinity: {}

  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

# Node driver decorations
node:

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  labels: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  nodeSelector: {}

  # These values map directly to yaml in the deployment spec, see the kubernetes docs for info
  tolerations: []

  affinity: {}

  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

# imagePullPolicy applied for all hpe-csi-driver images
imagePullPolicy: "IfNotPresent"

# Release images
images:
  csiNodeInit: quay.io/hpestorage/filex-csi-init:2.6.4
  csiNodeDriver: quay.io/hpestorage/filex-csi-driver:2.6.4
  csiControllerDriver: quay.io/hpestorage/filex-csi-driver:2.6.4
  csiAttacher: registry.k8s.io/sig-storage/csi-attacher:v4.8.0
  csiNodeDriverRegistrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0
  csiProvisioner: registry.k8s.io/sig-storage/csi-provisioner:v6.1.0
  csiResizer: registry.k8s.io/sig-storage/csi-resizer:v1.12.0
  csiSnapshotter: registry.k8s.io/sig-storage/csi-snapshotter:v8.4.0
