apiVersion: v1
version: "2.5.0-beta4"
appVersion: "2.5.0-beta4"
annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: storage
  artifacthub.io/links: |
    - name: Release Highlights
      url: https://scod.hpedev.io/csi_driver/index.html#latest_release
    - name: Release Notes
      url: https://github.com/hpe-storage/csi-driver/tree/master/release-notes
    - name: Documentation
      url: https://scod.hpedev.io/csi_driver
    - name: Chart Source
      url: https://github.com/hpe-storage/co-deployments
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/olm/community-operators/hpe-csi-operator
    - url: https://artifacthub.io/packages/helm/hpe-storage/hpe-csi-info-metrics
    - url: https://artifacthub.io/packages/helm/hpe-storage/hpe-array-exporter
description: A Helm chart for installing the HPE CSI Driver for Kubernetes
icon: https://raw.githubusercontent.com/hpe-storage/co-deployments/master/docs/assets/hpedev.png
maintainers:
- name: datamattsson
  email: dev-hi-containers@hpe.com
sources:
- https://github.com/hpe-storage/csi-driver
name: hpe-csi-driver
home: https://hpe.com/storage/containers
keywords:
  - HPE
  - Storage
  - CSI
