apiVersion: v1
version: "1.5.0-beta"
appVersion: "1.5.0-beta"
annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
  - name: Documentation
    url: https://scod.hpedev.io/csi_driver
description: A Helm chart for installing the HPE CSI Driver for Kubernetes
icon: https://raw.githubusercontent.com/hpe-storage/co-deployments/master/docs/assets/hpedev.png
maintainers:
- name: raunakkumar
  email: hpe-containers-dev@hpe.com
sources:
- https://github.com/hpe-storage/co-deployments
- https://github.com/hpe-storage/csi-driver
name: hpe-csi-driver
home: https://hpe.com/storage/containers
keywords:
  - HPE
  - Storage
  - CSI
