---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hpe-csi-info-metrics-serviceaccount
  namespace: {{ .Release.Namespace }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpe-csi-info-metrics-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hpe-csi-info-metrics-rolebinding
subjects:
  - kind: ServiceAccount
    name: hpe-csi-info-metrics-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: hpe-csi-info-metrics-role
  apiGroup: rbac.authorization.k8s.io

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hpe-csi-info-metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: hpe-csi-info-metrics
  replicas: 1
  template:
    metadata:
      labels:
        app: hpe-csi-info-metrics
    spec:
      serviceAccount: hpe-csi-info-metrics-serviceaccount
      containers:
        - name: csi-info-metrics
          {{- if .Values.registry }}
          image: {{ .Values.registry }}/hpestorage/csi-info-metrics:rkumpf
          {{- else }}
          image: quay.io/hpestorage/csi-info-metrics:v1.0.0
          {{- end }}
          ports:
          - containerPort: 9099
          args:
            - "--telemetry.addr=:9099"
            - "--telemetry.path=/metrics"
            {{- if .Values.acceptEula }}
            - "--accept-eula"
            {{- end }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}

---
{{- $service := .Values.service | default dict }}
kind: Service
apiVersion: v1
metadata:
  name: hpe-csi-info-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: hpe-csi-info-metrics-service
    {{- range $key, $value := $service.customLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- $serviceType := $service.type | default "ClusterIP" }}
  type: {{ $serviceType | quote }}
  ports:
    - name: http-metrics
      port: {{ $service.port | default 9090 }}
      {{- if eq $serviceType "NodePort" }}
      {{- if $service.nodePort }}
      nodePort: {{ $service.nodePort }}
      {{- end }}
      {{- end }}
      protocol: TCP
      targetPort: 9099
  selector:
    app: hpe-csi-info-metrics
